-- use database
USE ufc;

-- =====================================================
-- FULL RESET
-- =====================================================
DROP TABLE IF EXISTS fights;
DROP TABLE IF EXISTS fighters;
DROP TABLE IF EXISTS divisions;
DROP TABLE IF EXISTS events;

-- =====================================================
-- SCHEMA
-- =====================================================
CREATE TABLE divisions (
    weight_class_id INT AUTO_INCREMENT PRIMARY KEY,
    class_name VARCHAR(50),
    gender ENUM('Male', 'Female') NOT NULL
);

CREATE TABLE fighters (
    fighter_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    nickname VARCHAR(50),
    gender ENUM('Male', 'Female'),
    weight_class_id INT,
    country VARCHAR(50),
    CONSTRAINT fk_fighter_division 
        FOREIGN KEY (weight_class_id) REFERENCES divisions(weight_class_id)
);

CREATE TABLE events (
    event_id INT AUTO_INCREMENT PRIMARY KEY,
    edition_number INT,
    event_name VARCHAR(120) NOT NULL,
    event_date DATE,
    location_name VARCHAR(200)
);

CREATE TABLE fights (
    fight_id INT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    fighter_red INT NOT NULL,
    fighter_blue INT NOT NULL,
    winner INT NULL,
    method VARCHAR(80),
    round_number INT,
    notes TEXT,
    CONSTRAINT fk_fights_event FOREIGN KEY (event_id) REFERENCES events(event_id),
    CONSTRAINT fk_fights_red FOREIGN KEY (fighter_red) REFERENCES fighters(fighter_id),
    CONSTRAINT fk_fights_blue FOREIGN KEY (fighter_blue) REFERENCES fighters(fighter_id),
    CONSTRAINT fk_fights_winner FOREIGN KEY (winner) REFERENCES fighters(fighter_id)
);

-- =====================================================
-- SEED DATA
-- =====================================================
INSERT INTO divisions (class_name, gender) VALUES
('Flyweight', 'Male'),
('Bantamweight', 'Male'),
('Featherweight', 'Male'),
('Lightweight', 'Male'),
('Welterweight', 'Male'),
('Middleweight', 'Male'),
('Light Heavyweight', 'Male'),
('Heavyweight', 'Male'),
('Strawweight', 'Female'),
('Flyweight', 'Female'),
('Bantamweight', 'Female'),
('Featherweight', 'Female');

INSERT INTO fighters (first_name, last_name, nickname, gender, weight_class_id, country) VALUES
('Conor', 'McGregor', 'The Notorious', 'Male', 4, 'Ireland'),
('Khabib', 'Nurmagomedov', 'The Eagle', 'Male', 4, 'Russia'),
('Amanda', 'Nunes', 'The Lioness', 'Female', 11, 'Brazil'),
('Jon', 'Jones', 'Bones', 'Male', 7, 'USA'),
('Valentina', 'Shevchenko', 'Bullet', 'Female', 10, 'Kyrgyzstan'),
('Islam', 'Makhachev', NULL, 'Male', 5, 'Russia'),
('Ilia', 'Topuria', 'El Matador', 'Male', 4, 'Spain'),
('Merab', 'Dvalishvili', 'The Machine', 'Male', 2, 'Georgia'),
('Khamzat', 'Chimaev', 'Borz', 'Male', 6, 'Russia'),
('Alexandre', 'Pantoja', 'The Cannibal', 'Male', 1, 'Brazil'),
('Alex', 'Pereira', 'Poatan', 'Male', 7, 'Brazil'),
('Alexander', 'Volkanovski', 'The Great', 'Male', 3, 'Australia'),
('Tom', 'Aspinall', NULL, 'Male', 8, 'England'),
('Dricus', 'Du Plessis', 'Stillknocks', 'Male', 6, 'South Africa'),
('Max', 'Holloway', 'Blessed', 'Male', 4, 'USA'),
('Jack', 'Della Maddalena', 'JDM', 'Male', 5, 'Australia'),
('Magomed', 'Ankalaev', 'Big Ank', 'Male', 7, 'Russia'),
('Arman', 'Tsarukyan', 'Ahalkalakets', 'Male', 4, 'Armenia'),
('Charles', 'Oliveira', 'Do Bronx', 'Male', 4, 'Brazil'),
('Belal', 'Muhammad', 'Remember the Name', 'Male', 5, 'USA'),
('Joshua', 'Van', 'The Fearless', 'Male', 1, 'Burma'),
('Brandon', 'Moreno', 'The Assasin Baby', 'Male', 1, 'Mexico'),
('Brandon', 'Royval', 'Raw Dawg', 'Male', 1, 'USA'),
('Amir', 'Albazi', 'The Prince', 'Male', 1, 'Iraq'),
('Tatsuro', 'Taira', 'The Best', 'Male', 1, 'Japan'),
('Manel', 'Kape', 'Starboy', 'Male', 1, 'Angola'),
('Asu', 'Almabayev', 'Zulfikar', 'Male', 1, 'Kazakhstan'),
('Kyoji', 'Horiguchi', 'The Typhoon', 'Male', 1, 'Japan'),
('Tim', 'Elliott', 'MacGyver', 'Male', 1, 'USA'),
('Steve', 'Erceg', 'AstroBoy', 'Male', 1, 'Australia'),
('Alex', 'Perez', 'The Decision', 'Male', 1, 'USA'),
('Tagir', 'Ulanbekov', NULL, 'Male', 1, 'Russia'),
('Charles', 'Johnson', 'Big Money', 'Male', 1, 'USA'),
('Bruno', 'Silva', 'Blindado', 'Male', 1, 'Brazil'),
('Loneer', 'Kavanagh', NULL, 'Male', 1, 'England'),
('Umar', 'Nurmagomedov', 'Young Eagle', 'Male', 2, 'Russia'),
('Sean', 'O\'Malley', 'Suga', 'Male', 2, 'USA'),
('Petr', 'Yan', 'No Mercy', 'Male', 2, 'Russia'),
('Cory', 'Sandhagen', 'The Sandman', 'Male', 2, 'USA'),
('Song', 'Yadong', 'Kung Fu King', 'Male', 2, 'China'),
('Deiveson', 'Figueiredo', 'Deus da Guerra', 'Male', 2, 'Brazil'),
('Aiemann', 'Zahabi', NULL, 'Male', 2, 'Canada'),
('Marlon', 'Vera', 'Chito', 'Male', 2, 'Ecuador'),
('Mario', 'Bautista', 'Raider', 'Male', 2, 'USA'),
('Henry', 'Cejudo', 'Triple C', 'Male', 2, 'USA'),
('David', 'Martinez', 'Black Spartan', 'Male', 2, 'Mexico'),
('Rob', 'Font', NULL, 'Male', 2, 'USA'),
('Vinicius', 'Oliveira', 'LokDog', 'Male', 2, 'Brazil'),
('Kyler', 'Phillips', 'The Matrix', 'Male', 2, 'USA'),
('Marcus', 'McGhee', 'The Maniac', 'Male', 2, 'USA'),
('Movsar', 'Evloev', NULL, 'Male', 3, 'Russia'),
('Diego', 'Lopes', NULL, 'Male', 3, 'Brazil'),
('Yair', 'Rodriguez', 'El Pantera', 'Male', 3, 'Mexico'),
('Lerone', 'Murphy', 'The Miracle', 'Male', 3, 'England'),
('Aljamain', 'Sterling', 'Funk Master', 'Male', 3, 'USA'),
('Arnold', 'Allen', 'Almighty', 'Male', 3, 'England'),
('Youssef', 'Zalal', 'The Moroccan Devil', 'Male', 3, 'Morroco'),
('Steve', 'Garcia', 'Mean Machine', 'Male', 3, 'USA'),
('Brian', 'Ortega', 'T-City', 'Male', 3, 'USA'),
('Josh', 'Emmett', 'CC0', 'Male', 3, 'USA'),
('Jean', 'Silva', 'Lord Assasin', 'Male', 3, 'Brazil'),
('Patricio', 'Freire', 'Patricio Pitbull', 'Male', 3, 'Brazil'),
('Dan', 'Ige', '50K', 'Male', 3, 'USA'),
('David', 'Onama', 'Silent Assasin', 'Male', 3, 'Uganda'),
('Giga', 'Chikadze', 'Ninja', 'Male', 3, 'Georgia'),
('Justin', 'Gaethje', 'The Highlight', 'Male', 4, 'USA'),
('Paddy', 'Pimblett', 'The Baddy', 'Male', 4, 'England'),
('Dan', 'Hooker', 'The Hangman', 'Male', 4, 'New Zealand'),
('Mateusz', 'Gamrot', 'Gamer', 'Male', 4, 'Poland'),
('Benoit', 'Saint Denis', 'God of War', 'Male', 4, 'France'),
('Rafael', 'Fiziev', 'Ataman', 'Male', 4, 'Kazakhstan'),
('Renato', 'Alves', 'Moicano', 'Male', 4, 'Brazil'),
('Michael', 'Chandler', 'Iron', 'Male', 4, 'USA'),
('Beneil', 'Dariush', 'Benny', 'Male', 4, 'USA'),
('Grant', 'Dawson', 'KGD', 'Male', 4, 'USA'),
('Mauricio', 'de Lima Santos', 'Ruffy', 'Male', 4, 'Brazil'),
('Ignacio', 'Bahamondes', 'La Jaula', 'Male', 4, 'Chile'),
('Ian', 'Machado Garry', 'The Future', 'Male', 5, 'Ireland'),
('Shavkat', 'Rakhmonov', 'Nomad', 'Male', 5, 'Kazakhstan'),
('Michael', 'Morales', NULL, 'Male', 5, 'Ecuador'),
('Carlos', 'Prates', 'The Nightmare', 'Male', 5, 'Brazil'),
('Sean', 'Brady', NULL, 'Male', 5, 'USA'),
('Kamaru', 'Usman', 'Marty', 'Male', 5, 'Nigeria'),
('Leon', 'Edwards', 'Rocky', 'Male', 5, 'England'),
('Joaquin', 'Buckley', 'New Mansa', 'Male', 5, 'USA'),
('Gabriel', 'Bonfim', 'Marretinha', 'Male', 5, 'Brazil'),
('Gilbert', 'Burns', 'Durinho', 'Male', 5, 'Brazil'),
('Colby', 'Covington', 'Chaos', 'Male', 5, 'USA'),
('Geoff', 'Neal', 'Handz of Steel', 'Male', 5, 'USA'),
('Daniel', 'Rodriguez', 'D-Rod', 'Male', 5, 'USA'),
('Nassourdine', 'Imavov', 'The Sniper', 'Male', 6, 'France'),
('Sean', 'Strickland', 'Tarzan', 'Male', 6, 'USA'),
('Anthony', 'Hernandez', 'Fluffy', 'Male', 6, 'USA'),
('Brendan', 'Allen', 'All In', 'Male', 6, 'USA'),
('Israel', 'Adesanya', 'The Last Stylebender', 'Male', 6, 'Nigeria'),
('Caio', 'Borralho', 'The Natural', 'Male', 6, 'Brazil'),
('Reinier', 'De Ridder', 'The Dutch Knight', 'Male', 6, 'Netherlands'),
('Robert', 'Whittaker', 'The Reaper', 'Male', 6, 'Australia'),
('Jared', 'Cannonier', 'The Killa Gorilla', 'Male', 6, 'USA'),
('Michael', 'Page', 'Venom', 'Male', 6, 'England'),
('Roman', 'Dolidze', 'The Caucasian', 'Male', 6, 'Georgia'),
('Paulo', 'Costa', 'The Eraser', 'Male', 6, 'Brazil'),
('Marvin', 'Vettori', 'The Italian Dream', 'Male', 6, 'Italy'),
('Gregory', 'Rodrigues', 'Robocop', 'Male', 6, 'Brazil'),
('Jiri', 'Prochazka', 'The Czech Samurai', 'Male', 7, 'Czechia'),
('Carlos', 'Ulberg', 'Black JAG', 'Male', 7, 'New Zealand'),
('Khalil', 'Rountree Jr', 'The War Horse', 'Male', 7, 'USA'),
('Jan', 'Blachowicz', 'The Polish Power', 'Male', 7, 'Poland'),
('Jamahal', 'Hill', 'Sweet Dreams', 'Male', 7, 'USA'),
('Azamat', 'Murzakanov', 'The Professional', 'Male', 7, 'Russia'),
('Dominick', 'Reyes', 'The Devastator', 'Male', 7, 'USA'),
('Volkan', 'Oezdemir', 'No Time', 'Male', 7, 'Switzerland'),
('Aleksandar', 'Rakic', 'Rocket', 'Male', 7, 'Austria'),
('Bogdan', 'Guskov', 'Czarevitch', 'Male', 7, 'Uzbekistan'),
('Walker Johnny', 'Silva', 'Johnny Walker', 'Male', 7, 'Brazil'),
('Nikita', 'Krylov', 'The Miner', 'Male', 7, 'Ukraine'),
('Zhang', 'Mingyang', 'Mountain Tiger', 'Male', 7, 'China'),
('Alonzo', 'Menifield', 'Atomic', 'Male', 7, 'USA'),
('Ciryl', 'Gane', 'Bon Gamin', 'Male', 8, 'France'),
('Alexander', 'Volkov', 'Drago', 'Male', 8, 'Russia'),
('Sergei', 'Pavlovich', 'The Spartan', 'Male', 8, 'Russia'),
('Curtis', 'Blaydes', 'Razor', 'Male', 8, 'USA'),
('Waldo', 'Cortes Acosta', 'Salsa Boy', 'Male', 8, 'Dominican Republic'),
('Jailton', 'Almeida', 'Malhadinho', 'Male', 8, 'Brazil'),
('Serghei', 'Spivac', 'The Polar Bear', 'Male', 8, 'Moldova'),
('Derrick', 'Lewis', 'he Black Beast', 'Male', 8, 'USA'),
('Ante', 'Delija', 'Walking Trouble', 'Male', 8, 'Croatia'),
('Marcin', 'Tybura', 'Tybur', 'Male', 8, 'Poland'),
('Shamil', 'Gaziev', NULL, 'Male', 8, 'Russia'),
('Tai', 'Tuivasa', 'Bam Bam', 'Male', 8, 'Australia'),
('Mick', 'Parkin', NULL, 'Male', 8, 'England'),
('Valter', 'Walker', 'The Clean Monster', 'Male', 8, 'Brazil'),
('Tallison', 'Teixeira', NULL, 'Male', 8, 'Brazil'),
('Zhang', 'Weili', 'Magnum', 'Female', 9, 'China'),
('Tatiana', 'Suarez', NULL, 'Female', 9, 'USA'),
('Virna', 'Jandiroba', 'Carcara', 'Female', 9, 'Brazil'),
('Yan', 'Xiaonan', 'Nine', 'Female', 9, 'China'),
('Amanda', 'Lemos', 'Amandinha', 'Female', 9, 'Brazil'),
('Loopy', 'Godinez', 'Loopy', 'Female', 9, 'Mexico'),
('Iasmin', 'Lucindo', NULL, 'Female', 9, 'Brazil'),
('Tabatha', 'Ricci', 'Baby Shark', 'Female', 9, 'Brazil'),
('Jessica', 'Andrade', 'Bate Estaca', 'Female', 9, 'Brazil'),
('Gillian', 'Robertson', 'The Savage', 'Female', 9, 'Canada'),
('Amanda', 'Ribas', NULL, 'Female', 9, 'Brazil'),
('Fatima', 'Kline', 'The Archangel', 'Female', 9, 'USA'),
('Denise', 'Gomes', 'Dee', 'Female', 9, 'Brazil'),
('Angela', 'Hill', 'Overkill', 'Female', 9, 'USA'),
('Alexia', 'Thainara', 'Burguesinha', 'Female', 9, 'Brazil'),
('Manon', 'Fiorot', 'The Beast', 'Female', 10, 'France'),
('Natalia', 'Silva', NULL, 'Female', 10, 'Brazil'),
('Alexa', 'Grasso', NULL, 'Female', 10, 'Mexico'),
('Erin', 'Blanchfield', 'Cold Blooded', 'Female', 10, 'USA'),
('Maycee', 'Barber', 'The Future', 'Female', 10, 'USA'),
('Rose', 'Namajunas', 'Thug', 'Female', 10, 'USA'),
('Jasmine', 'Jasudavicius', 'Vicious', 'Female', 10, 'Canada'),
('Tracy', 'Cortez', NULL, 'Female', 10, 'USA'),
('Karine', 'Silva', 'Killer', 'Female', 10, 'Brazil'),
('Miranda', 'Maverick', 'Fear The', 'Female', 10, 'USA'),
('Casey', 'ONeill', 'King', 'Female', 10, 'Australian'),
('Wang', 'Cong', 'The Joker', 'Female', 10, 'China'),
('Eduarda', 'Moura', 'Ronda', 'Female', 10, 'Brazil'),
('JJ', 'Aldrich', 'Dreamchaser', 'Female', 10, 'USA'),
('Gabriella', 'Fernandes', 'Gabi', 'Female', 10, 'Brazil'),
('Julianna', 'Peña', 'The Venezuelan Vixen', 'Female', 11, 'USA'),
('Raquel', 'Pennington', 'Rocky', 'Female', 11, 'USA'),
('Norma', 'Dumont', 'The Immortal', 'Female', 11, 'Brazil'),
('Ketlen', 'Vieira', 'Fenomeno', 'Female', 11, 'Brazil'),
('Yana', 'Santos', 'Foxy', 'Female', 11, 'Russia'),
('Irene', 'Aldana', NULL, 'Female', 11, 'Mexico'),
('Macy', 'Chiasson', NULL, 'Female', 11, 'USA'),
('Ailin', 'Perez', 'Fiora', 'Female', 11, 'Argentina'),
('Karol', 'Rosa', NULL, 'Female', 11, 'Brazil'),
('Jacqueline', 'Cavalcanti', 'The Nightmare', 'Female', 11, 'Portugal'),
('Mayra', 'Bueno Silva', 'Sheetara', 'Female', 11, 'Brazil'),
('Nora', 'Cornolle', 'Wonder', 'Female', 11, 'France'),
('Miesha', 'Tate', 'Cupcake', 'Female', 11, 'USA'),
('Joselyne', 'Edwards', 'La Pantera', 'Female', 11, 'Panama'),
('Luana', 'Santos', NULL, 'Female', 11, 'Brazil'),
('Kayla', 'Harrison', 'Doug', 'Female', 12, 'USA');

INSERT INTO events (edition_number, event_name, event_date, location_name) VALUES
(295, 'UFC 295: Prochazka vs Pereira', '2023-11-11', 'Madison Square Garden, New York'),
(296, 'UFC 296: Edwards vs Covington', '2023-12-16', 'Las Vegas, Nevada');

INSERT INTO fights (event_id, fighter_red, fighter_blue, winner, method, round_number, notes) VALUES
(1, 1, 2, 2, 'Submission', 4, 'Rear-naked choke'),
(1, 3, 5, 3, 'Decision', 5, 'Split decision'),
(2, 4, 1, 4, 'KO', 1, 'Head kick'),
(2, 2, 1, NULL, 'Scheduled', NULL, 'Fight has not occurred yet');

